config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :new, :create]
  root "games#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :get_game, only: [:index, :new]
  def index
    @game = Game.new
  end

  def new
    @board = Game.new
  end

  def create
    @board = GameGeneratorService.new(params).generate_game
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  private

  def get_game
    @game = Game.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_new.html.erb
<div align="center">
  <%if board.present? %>
    <table cellspacing="2" width="200px" id="game_board" border="1px">
    <% board&.each do |row| %>
    <tr>
      <% row&.each do |row_val| %>
      <td align="center"><img src="images/covered_tile.png" alt="" border=3 height=30 width=30 value="<%= row_val %>"></img></td>
      <% end %>
    </tr>
    <% end %>
    </table>
  <%end%>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    var table = document.getElementById("game_board");
    var cells = table.getElementsByTagName("td"); //
    setTotalCells(cells);
    for(var i = 0; i < cells.length; i++){
        // Cell Object
        var cell = cells[i];
        // Track with onclick
        cell.onclick = function(){
            img = this.getElementsByTagName('img')[0];
            img_val = img.getAttribute('value');
            checkWinStatus(cells, img_val);
            if (img_val == '0'){
              revealNeighbours(); // TODO reveal other neighbours
              this.innerHTML = ""; // Set null value in td
            }
            else if(img_val == '1' || img_val == '2' || img_val == '3' || img_val == '4' || img_val == '5' || img_val == '6' || img_val == '7' || img_val == '8'){
              this.innerHTML = img_val; // Set value on image to the td
            }
            else if(img_val == 'x'){
              // Reset timer
              resetTimer();
              document.getElementById("seconds").innerHTML='00';
              document.getElementById("minutes").innerHTML='00';
              //
              $('#gameOver').val(true);
              document.getElementById("lost").innerHTML='Sorry ! You lost, please start a new game'; // Lost message
              this.innerHTML = "<img src='images/mine_blown.jpg' alt='' border=3 height=30 width=30></img>" // Set clicked mine to blown
              revealAllMines(cells); // Reveal all other mines on the booard
            }
        };
        cell.oncontextmenu = function (){
          this.innerHTML = "<img src='images/flag.png' alt='' border=3 height=30 width=30 value='flagged'></img>" // Set clicked mine to blown
          return false;
        }
    }
  });
</script>

app/views/games/_start_menu.html.erb
<div class="col-md-12" >
<%=  form_for @game, url: games_path(format: :js), method: 'post', remote: true do |f| %>
   <div style="margin-left: 100px;">
    <h3>Select game mode </h5>
    <table cellspacing="0" cellpadding="2" id="options" class="dialog" style="display: table;table-layout: fixed">
          <tbody><tr class="dialog-title">
            <td colspan="3" style="padding: 3px; text-align: right;">
            </td>
          </tr>
          <tr class="dialog-bar">
            <td></td>
            <td>Height</td>
            <td>Width</td>
            <td>Mines</td>
          </tr>
          <tr>
            <td><label><%= radio_button_tag "difficulty", 'beginner', 'beginner' %><%= label_tag "Beginner" %></label></td>
            <td>9</td>
            <td>9</td>
            <td>10</td>
          </tr>
          <tr>
            <td><label><%= radio_button_tag "difficulty", 'intermediate' %><%= label_tag "Intermediate" %></label></td>
            <td>16</td>
            <td>16</td>
            <td>40</td>
          </tr>
          <tr>
            <td><label><%= radio_button_tag "difficulty", 'expert' %><%= label_tag "Expert" %></label></td>
            <td>16</td>
            <td>30</td>
            <td>99</td>
          </tr>
          <tr>
            <td><label><%= radio_button_tag "difficulty", 'custom' %><%= label_tag "custom" %></td>
            <td><%= f.text_field :height, required: true, class: 'form-control', value: '20'  %></td>
            <td><%= f.text_field :width, required: true, class: 'form-control', value: '30'  %></td>
            <td><%= f.text_field :mines, required: true, class: 'form-control', value: '145'  %></td>
          </tr>
          <tr class="dialog-bar">
            <td><input type="submit" value="New Game" style="vertical-align: middle;" onclick="startTimer();"></td>
            <td><%= button_tag "Controls", :type => 'button', :class => "subBtn", id: 'controls' %></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>Timer: <span id="minutes">00</span>:<span id="seconds">00</span></td>
          </tr>
        </tbody>
      </table>
      <div align="center" style="margin-right: 75px;"><strong><span id="lost"></span></strong></div>
      <input id="remainingCells" type="hidden" name="" value="0" >
      <input id="totalCells" type="hidden" name="" value="">
      <input id="gameOver" type="hidden" name="" value="false">
<%end %>
</div>
<div id="dialog_controls" title="Controls">
  <table cellspacing="0" cellpadding="2" id="controls" class="dialog" style="display: table;">
        <tbody>
          <tr class="dialog-title">
          <td>Controls</td>
        </tr>
        <tr>
          <td style="padding: 6px;"><strong>Desktop</strong></td>
          <td style="padding: 6px;">
            <ul>
              <li><b>Left-click</b> an empty square to reveal it.</li>
              <li><b>Right-click</b> (or <b>Ctrl+click</b>) an empty square to flag it.</li>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
</div>



<script>
  $( function() {
    $( "#dialog_controls" ).dialog({
      autoOpen: false,
      show: {
        effect: "blind",
        duration: 1000
      },
      hide: {
        effect: "explode",
        duration: 1000
      }
    });

    $( "#controls" ).on( "click", function() {
      $( "#dialog_controls" ).dialog( "open" );
    });
  } );
  </script>

app/views/games/create.js.erb
$("#board").html("<%= escape_javascript(render partial: 'new', locals: {board: @board} ) %>");

app/views/games/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag('game_manager', 'data-turbolinks-track': 'reload') %>
<% end %>
<h1 align='center'>Welcome to MineSweeper </h1>
<%= render partial: 'games/start_menu' %>
<div id="board">
  <%= render partial: "new", locals: {board: @board} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <%= content_for :head %>
    </head>

  <body>
    <%= yield %>
  </body>
</html>